# Generated by Django 4.0.3 on 2022-03-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentic', '0002_alter_botuser_options_remove_botuser_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AlterModelOptions(
            name='botuser',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='procedure',
            options={'verbose_name': 'Процедура', 'verbose_name_plural': 'Процедуры'},
        ),
        migrations.AlterField(
            model_name='botuser',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создать время'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='diagnosis',
            field=models.ManyToManyField(to='dentic.diagnosis'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='treatment',
            field=models.ManyToManyField(to='dentic.treatment'),
        ),
    ]
