# Generated by Django 4.0.3 on 2022-03-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentic', '0003_diagnosis_treatment_alter_botuser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentalFilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='procedure',
            name='dental_filling',
            field=models.ManyToManyField(to='dentic.dentalfilling'),
        ),
    ]
